
Region: us-east-1
Image:
  Os: alinux2

HeadNode:
  InstanceType: c5a.2xlarge
  Ssh:
    KeyName: aws-us-est1
  Networking:
    SubnetId: subnet-0b4cb121b9aba89f1
  LocalStorage:
    RootVolume:
      Size: 500
      VolumeType: gp3
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
  Dcv:
    Enabled: False
  CustomActions:
    OnNodeConfigured:
      Script: https://raw.githubusercontent.com/wangsl/aws-test/main/aws-post-01.bash

Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: spot
      ComputeResources:
        - Name: c5n18xlarge
          MinCount: 0
          MaxCount: 1000
          InstanceType: c5n.18xlarge
          Efa:
            Enabled: true
          DisableSimultaneousMultithreading: true
        - Name: c6i32xlarge
          MinCount: 0
          MaxCount: 100
          InstanceType: c6i.32xlarge
          Efa:
            Enabled: true
          DisableSimultaneousMultithreading: true
        - Name: p32xlarge
          MinCount: 0
          MaxCount: 10
          InstanceType: p3.2xlarge
          DisableSimultaneousMultithreading: false
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
      Networking:
        SubnetIds:
          - subnet-subnet-0b4cb121b9aba89f1
        PlacementGroup:
          Enabled: true
        AdditionalSecurityGroups:
          - sg-04ec976b09177c580
      CustomActions:
        OnNodeConfigured:
          Script: https://raw.githubusercontent.com/wangsl/aws-test/main/aws-post-01.bash

SharedStorage:
  - Name: FsxLustre0
    StorageType: FsxLustre
    MountDir: /scratch
    FsxLustreSettings:
      StorageCapacity: 1200
      DeploymentType: SCRATCH_2

      
