
Region: us-east-2
Image:
  Os: alinux2
  
HeadNode:
  InstanceType: c5a.2xlarge
  Ssh:
    KeyName: aws-us-est2
  Networking:
    SubnetId: subnet-01a3868361b728e2c
  LocalStorage:
    RootVolume:
      Size: 500
      VolumeType: gp3
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
  Dcv:
    Enabled: False
  CustomActions:
    OnNodeConfigured:
      Script: https://raw.githubusercontent.com/wangsl/aws-test/main/aws-post-01.bash

Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: c5n18xlarge
      CapacityType: SPOT
      ComputeResources:
        - Name: c5n18xlarge
          MinCount: 0
          MaxCount: 1000
          InstanceType: c5n.18xlarge
          Efa:
            Enabled: true
          DisableSimultaneousMultithreading: true
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
      Networking:
        SubnetIds:
          - subnet-01a3868361b728e2c
        AssignPublicIp: true
        PlacementGroup:
          Enabled: true
        AdditionalSecurityGroups:
          - sg-04ec976b09177c580
      CustomActions:
        OnNodeConfigured:
          Script: https://raw.githubusercontent.com/wangsl/aws-test/main/aws-post-01.bash

    - Name: c6i32xlarge
      CapacityType: SPOT
      ComputeResources: 
        - Name: c6i32xlarge
          MinCount: 0
          MaxCount: 1000
          InstanceType: c6i.32xlarge
          Efa:
            Enabled: true
          DisableSimultaneousMultithreading: true
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
      Networking:
        SubnetIds:
          - subnet-01a3868361b728e2c
        AssignPublicIp: false
        PlacementGroup:
          Enabled: true
        AdditionalSecurityGroups:
          - sg-04ec976b09177c580
      CustomActions:
        OnNodeConfigured:
          Script: https://raw.githubusercontent.com/wangsl/aws-test/main/aws-post-01.bash

    - Name: p32xlarge
      CapacityType: SPOT
      ComputeResources:
        - Name: p32xlarge
          MinCount: 0
          MaxCount: 100
          InstanceType: p3.2xlarge
          DisableSimultaneousMultithreading: false
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
      Networking:
        SubnetIds:
          - subnet-01a3868361b728e2c
        AssignPublicIp: true
      CustomActions:
        OnNodeConfigured:
          Script: https://raw.githubusercontent.com/wangsl/aws-test/main/aws-post-01.bash

    - Name: p38xlarge
      CapacityType: SPOT
      ComputeResources:
        - Name: p38xlarge
          MinCount: 0
          MaxCount: 100
          InstanceType: p3.8xlarge
          DisableSimultaneousMultithreading: false
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
      Networking:
        SubnetIds:
          - subnet-01a3868361b728e2c
        AssignPublicIp: true
      CustomActions:
        OnNodeConfigured:
          Script: https://raw.githubusercontent.com/wangsl/aws-test/main/aws-post-01.bash
          
SharedStorage:
  - Name: FsxLustre0
    StorageType: FsxLustre
    MountDir: /scratch
    FsxLustreSettings:
      StorageCapacity: 1200
      DeploymentType: SCRATCH_2
